# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

list1 = []
n = 0
i = 1
while(n!=10):
    list1.append(i**3)
    i = i+2
    n = n + 1
tuple1 = tuple(list1)
print(tuple1)