# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

def add_prefix_to_lines(text, indentation_text):
    lines = text.splitlines()
    lines[0] = indentation_text + lines[0]
    for line in lines:
        print(line)

# Example usage:
original_text = "Line 1\nLine 2\nLine 3"
indentation_text = "   "
add_prefix_to_lines(original_text,indentation_text)