# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K8BztIo6umoUVJKZ8xH1u2PSvbkL_KMK
"""

def new_String(s):
    i1 = s.find("not")
    i2 = s.find("poor")

    if(i1 != -1 and i2 != -1 and i1<i2):
        i3 = s.find("bad",i2)
        if(i3 != -1):
            s = s[:i1] + "good" + s[i3+3:]
            return s

user_input = input("Enter any String:")
s = new_String(user_input)

print(f"{s}")