# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

list1 = [1,12,34,546,567,765]
dict1 = {}
for i in range(len(list1)):
    dict1[i] = list1[i]

for i,j in dict1.items():
    print(f"Index {i} has value {j}")