# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

# Predefined list
original_list = [1, 2, 'apple', 'orange', 3.14, 'banana', 'grape', 'kiwi']

# Valid tuple with allowed values
valid_tuple = (1, 'orange', 'banana', 'kiwi')

# Creating a copy of the original list with only valid values
filtered_list = [item for item in original_list if item in valid_tuple]

# Printing the original and filtered lists
print("Original List:", original_list)
print("Filtered List:", filtered_list)