# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

def new_string(s):
    c = 0
    for i in range(0,4):
        if(s[i].isupper()):
            c=c+1
    if(c>=2):
        return s.upper()
    else:
        return s

s1 = input("Enter string:")
result = new_string(s1)
print(result)