# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

user_input = input("Enter any string:")
shift = int(input("Enter shift value:"))

new = ""

for i in range(len(user_input)):
    if(user_input[i].isupper()):
        if(ord(user_input[i])+shift >90):
            j = (ord(user_input[i])+shift)%91+65
            x = chr(j)
            new = new + x
        else:
            x = chr(ord(user_input[i])+shift)
            new = new + x
    if(user_input[i].islower()):
        if (ord(user_input[i]) + shift > 122):
            j = (ord(user_input[i]) + shift) % 123 + 97
            x = chr(j)
            new = new + x
        else:
            x = chr(ord(user_input[i]) + shift)
            new = new + x
    if(user_input[i].isdigit() or user_input[i].isalnum() == False ):
        new = new + user_input[i]

print(new)