# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

list1 = [1,12,34,546,567,765]
list2 = [2,454,67,87654,12335]

sum = 0
for i in list1:
    sum = sum + i
for j in list2:
    sum = sum + j
print(f"Sum of elements of both list is {sum}")