# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Mu7mK4-bQJwqTMNuis9LcLBIfMc1qfi
"""

integer_input = int(input("Enter the integer input:"))
float_input = float(input("Enter the floating point input:"))
if(float_input>3.14):
    print(integer_input*100)