# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

# Crating a tuple from a list

list1 = ['a','b','c']
tuple1 = tuple(list1)
print(tuple1)

# Creating a list from tuple

tuple2 = ('a','b','c')
list2 = list(tuple2)
print(list2)