# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Mu7mK4-bQJwqTMNuis9LcLBIfMc1qfi
"""

# Program to number of seconds in a day
day = float(input("Enter number of days:"))
seconds = day*24*60*60
print(f"{day} day(s) has {seconds} seconds")