# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

user_input = input("Enter any string:")
if(len(user_input)>1):
    print(user_input[0:len(user_input)-1])
else:
    print("")