# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JttHq2PyT9G8yq5Bbhsd3_zndaSr3osP
"""

import pandas as pd
import numpy as np

data = {
    'Roll Number': [101, 102, 103, 104],
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Total Marks': [450, 480, 420, 490],
    'Class': ['X', 'XI', 'X', 'XII']
}

df = pd.DataFrame(data)
print(df.sort_values(["Name","Total Marks"],ascending=[True,False]))