# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZQamPoJ7CjFYrumHYNvOyl4hCQ-RM-_A
"""

import numpy as np

np_arr = np.random.random((5,5))
print(f"Its dimensions are: {np_arr.ndim}")
print(f"Its shape is :{np_arr.shape}")
print(f"Its size is {np_arr.size}")
print(f"Its datatype is {np_arr.dtype}")
print(f"Its itemsize is {np_arr.itemsize}")

