# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Mu7mK4-bQJwqTMNuis9LcLBIfMc1qfi
"""

# To check whether number is positive, negative or zero
num = float(input("Enter any number:"))

if(num ==0):
    print("Number is equal to zero")
elif(num>0):
    print("Number is positive")
else:
    print("Number is negative")