# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

import random

user_input = input("Enter any string:")
shift = random.randint(0,25)


alphabet_mapping = {
    'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7, 'I': 8, 'J': 9,
    'K': 10, 'L': 11, 'M': 12, 'N': 13, 'O': 14, 'P': 15, 'Q': 16, 'R': 17, 'S': 18, 'T': 19,
    'U': 20, 'V': 21, 'W': 22, 'X': 23, 'Y': 24, 'Z': 25
}

new = ""

for i in range(len(user_input)):
    if(user_input[i].isupper()):
        j = ((ord(user_input[i])%65)*shift)%26
        for m,n in alphabet_mapping.items():
            if(n==j):
                new = new + m
    if(user_input[i].islower()):
        j = ((ord(user_input[i])%65) * shift) % 26
        for m, n in alphabet_mapping.items():
            if (n == j):
                new = new + m.lower()
    if(user_input[i].isdigit() or user_input[i].isalnum() == False ):
        new = new + user_input[i]

print(new)