# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

# Define two tuples
first_tuple = (1, 2, 3)
second_tuple = (4, 5, 6)

# Concatenate the tuples
concatenated_tuple = second_tuple + first_tuple

# Print the result
print("First Tuple:", first_tuple)
print("Second Tuple:", second_tuple)
print("Concatenated Tuple:", concatenated_tuple)