# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Mu7mK4-bQJwqTMNuis9LcLBIfMc1qfi
"""

user_input = int(input("Enter your age:"))
if (user_input>=21 and user_input<=35):
    print(f"Candidate is eligible to appear for exam.")
else:
    print(f"Candidate is not eligible to appear for exam.")