# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

n = int(input("Enter the value of n:"))

list1 = []

for i in range(n):
    x = 2*i-1
    list1.append(x)
for i in range(0,n):
    if(i%2==0):
        print(list1[i],end = " ")