# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

def insert_string(main_string, insert_string, position):
    result = main_string[:position] + insert_string + main_string[position:]
    return result


main_str = input("Enter the main string: ")
insert_str = input("Enter the string to insert: ")
insert_position = int(input("Enter the position to insert: "))

result = insert_string(main_str, insert_str, insert_position)
print(result)