# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

s = input("Enter any 10 digit mobile number:")
new = ""
if(len(s)==10):
    new = new + s[:3] + "-" + s[3:7]+"-"+s[7:]
    print(new)
else:
    print("Only enter a 10 digit number")