# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZQamPoJ7CjFYrumHYNvOyl4hCQ-RM-_A
"""

import numpy as np

np_arr = np.random.randint(low=0, high=100, size=(5,5,5))
arr_shape = np_arr.shape
print(np_arr)
for i in range(arr_shape[1]):
    print(f"Sum of column {i+1} is {np_arr[:,:,i].sum()}")

