# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

list1 = [1,12,34,546,567,765]
list2 = []
for i in range(-1,-(len(list1)),-1):
    list2.append(list1[i])

print(list2)