# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

list1 = [1,12,34,546,567,765]
list2 = [2,454,67,87654,12335]

list3 = list1
for i in range(0,len(list2)):
    list3.append(list2[i])
print(list3)