# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Mu7mK4-bQJwqTMNuis9LcLBIfMc1qfi
"""

n = int(input("Enter the value of n:"))

sum = 0
for i in range(1,n+1):
    sum = sum + i**2/i

print(f"Answer is {sum}")

