# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Mu7mK4-bQJwqTMNuis9LcLBIfMc1qfi
"""

m = int(input("Enter value of m:"))
n = int(input("Enter value of n:"))
if(m<=n):
    for i in range(1,n):
        if(i%m==0):
            print(i,end=' ')
else:
    print("Invalid Value")