# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Mu7mK4-bQJwqTMNuis9LcLBIfMc1qfi
"""

# To evaluate 100/0
print(100/0)
# It generates an division by zero error
# To report a Divide by Zero error we have to simply diveide nay number by zero
print(400/0)