# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

import random
list1 = []
for i in range(5):
    x = random.randint(1,10000000)
    list1.append(x)

sum = 0
for i in list1:
    sum = sum + i
mean = sum/5

print(f"Sum of values is {sum} and Mean is {mean}")