# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

user_input = input("Enter any string:")
n = int(input("Enter the value of n:"))
m = int(input("Enter the value of m:"))
new = ""
for i in range(m, m + n):
    if i < len(user_input):
        new += user_input[i]
    else:
        break

print(new)