# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

str1 = input("Enter string1:")
str2 = input("Enter string2:")

print(f"Value of string1 before swapping is {str1}")
print(f"Value of string2 before swapping is {str2}")

temp = str1
str1 = str2
str2 = temp
print(f"Value of string1 after swapping is {str1}")
print(f"Value of string2 after swapping is {str2}")