# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZQamPoJ7CjFYrumHYNvOyl4hCQ-RM-_A
"""

import numpy as np

np_arr = np.array([["Arts","Dance","Music"]])
np_arr  = np.vstack([np_arr,[["rahul","priya","rajni"],["aditya","alex","siya"],["rohan","manoj","ekansh"]]])
print(np_arr)

