# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RrTyusaElUsDEFrCSyJ9PaWz3Vpx1s04
"""

def new_string(s):
    if(len(s)<1):
        return ""
    new = ""
    for i in range(0,len(s)):
        if(i%2==0):
            new = new + s[i]
    return  new

user_input = input("Enter any string:")
result = new_string(user_input)
print(f"{result}")