# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

n = int(input("Enter the value of n:"))
print("Enter the values for list:")
list1 = []
c = 0
while(c!=n):
    x = int(input())
    list1.append(x)
    c = c + 1

value = int(input("Enter the value to be inserted:"))
pos = int(input("Enter the position it needs to be inserted:"))

if pos == 0:
    list1.insert(0, value)
else:
    c = n - pos
    list1.append(list1[n - 1])

    while c != pos:
        list1[n - 1] = list1[n - 2]
        n = n - 1
        c = c - 1

    list1[pos] = value
list1[pos] = value
print(list1)