# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Mu7mK4-bQJwqTMNuis9LcLBIfMc1qfi
"""

num = int(input("Enter any number:"))
count = 0
n = num
while(num!=0):
    num=num//10
    count = count +1
print(f"Number of digits in {n} is {count}")

