# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

# Creating a tuple with one element containing three sub-elements
my_tuple = (('a', 'b', 'c'),)

# Printing the length of the tuple
print("Length of the tuple:", len(my_tuple))