# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

def remove_character(input_string, character_to_remove):
    modified_string = input_string.replace(character_to_remove, '')
    return modified_string

# Example usage:
user_input = input("Enter a string: ")
character_to_remove = input("Enter the character to remove: ")
result = remove_character(user_input, character_to_remove)
print(result)