# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Mu7mK4-bQJwqTMNuis9LcLBIfMc1qfi
"""

import math

num = float(input("Enter any number:"))
if(num >=0):
    print(f"Square root of {num} is {math.sqrt(num)}")
else:
    print("Square root of negative numbers does not exist")