# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

text = ("Line 1\nLine 2 3\nLine 3")
lines = text.split("\n")
words = text.split()
characters = len(text)
print(len(lines),len(words),characters)