# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

tuple1 = (1, 2, 3, 4, 5)
tuple2 = (1, 2)

for i in tuple2:
    if i not in tuple1:
        print("tuple2 is not a subset of tuple1")
        break
else:
    print("tuple2 is a subset of tuple1")