# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RrTyusaElUsDEFrCSyJ9PaWz3Vpx1s04
"""

def remove_character(s,i):
    if(len(s)<1):
        return ""
    elif(i>len(s)-1 or i<-len(s)):
        return "Wrong index entered"
    else:
        new = s[:i] + s[i+1:]
        return new

user_input = input("Enter any string:")
index = int(input("Enter any index:"))
result = remove_character(user_input,index)
print(f"{result}")