# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

def mirror_image(s):
    reverse = s[::-1]
    new = s+reverse
    return new

user_input = input("Enter string:")
result = mirror_image(user_input)
print(result)