# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1roF59jyJ80Gy5dh1yKNt9hnp6Hl6Mc6z
"""

# To swap two numbers using a temporary variable
num1 = 10
num2 = 15

print(f"Value of num1 before swapping is {num1}")
print(f"Value of num2 before swapping is {num2}")

temp = num1
num1 = num2
num2 = temp

print(f"Value of num1 after swapping is {num1}")
print(f"Value of num2 after swapping is {num2}")