# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

str1 = "hello"
str2 = "good to see"
str3 = "you"

str4 = " ".join([str1,str2])
str5 = " ".join([str4,str3])
print(str5)