# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1roF59jyJ80Gy5dh1yKNt9hnp6Hl6Mc6z
"""

str1 = input("Enter a string in uppercase:")
if(str1.isupper()):
    print(str1.lower())
else:
    print("Input is not entered in uppercase")