# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1roF59jyJ80Gy5dh1yKNt9hnp6Hl6Mc6z
"""

# To print ascii value of character
print(ord("a"))
print(ord("Z"))
print(ord(","))
print(ord("!"))
print(ord(" "))
print(ord("5"))