# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K8BztIo6umoUVJKZ8xH1u2PSvbkL_KMK
"""

# To find length of string
user_input = input("Enter any string:")

length = 0
for i in user_input:
    length += 1

print(f"Length of a string is {length}")