# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Mu7mK4-bQJwqTMNuis9LcLBIfMc1qfi
"""

import math

for i in range(0,361,45):
    print(f"sin({i}) is {math.sin(((i*math.pi)/180))}")

