# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

def new_string(s):
    list1 = []
    for i in s:
        list1.append(i)
    sorted_list = sorted(list1)
    new = ""
    for i in sorted_list:
        new = new + i

    return new

s1 = input("Enter string:")
result = new_string(s1)
print(result)