# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

def hasDigit(num):
    c = 0
    for i in num:
        if(i.isdigit()):
            c = c + 1
        else:
            continue
    if(c>0):
        return True
    else:
        return False

print("Input any five words:")
list1 = []
while(True):
    if(len(list1) == 5):
        break
    user_input = input("")
    if(len(user_input)<8 or hasDigit(user_input) == False):
        print("Enter word again")
        continue
    else:
        list1.append(user_input)

for i in list1:
    print(i,end = ",")