# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

n = int(input("Enter the value of n:"))
print("Enter the values for list:")
c = 0
sum = 0
list1 = []
while(c!=n):
    x = int(input())
    list1.append(x)
    c = c + 1
for i in range(0,n,1):
    if(list1[i]%2==0):
        sum = sum + list1[i]

print(f"Sum of all even numbers in a list is {sum}")