# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

user_input = int(input("Enter a number:"))
new_num = str(user_input)
list1 = []
for i in new_num:
    list1.append(i)

# Center align
list2 = [0]*10
c = 0
if (len(list1) > 10):
    print(user_input)
else:
    for i in range(10):
        if(len(list1)%2 != 0):
            if(i>=(5-len(list1)//2)-1 and i<(5-len(list1)//2)-1+len(list1)):
                list2[i] = list1[c]
                c = c + 1
            else:
                list2[i] = " "
        if(len(list1)%2==0):
            if(i>=(5-len(list1)//2) and i<(5-len(list1)//2)+len(list1)):
                list2[i] = list1[c]
                c = c + 1
            else:
                list2[i] = " "
    print(list2)
    new_str = ""
    for i in list2:
        new_str = new_str + i
    print(new_str)

# Left Align
list3 = [0]*10
c = 0
if (len(list1) > 10):
    print(user_input)
else:
    for i in range(10):
        if(i<len(new_num)):
            list3[i] = new_num[c]
            c = c + 1
        else:
            list3[i] = " "
    print(list3)
    new_str = ""
    for i in list3:
        new_str = new_str + i
    print(new_str)

# Right ALign Align
list4 = [0]*10
c = 0
if (len(list1) > 10):
    print(user_input)
else:
    for i in range(9,-1,-1):
        if(i>=(10-len(new_num))):
            list4[i] = new_num[c]
            c = c + 1
        else:
            list4[i] = " "
    print(list4)
    new_str = ""
    x = len(new_num)
    c = 1
    for i in range(10):
        if(list4[i] != ' '):
            new_str = new_str + list4[i+x-c]
            x = x - 1
            c = c + 1
        else:
            new_str = new_str + ' '
    print(new_str)

# To reverse words in a string
def reverse_words(input_string):
    words = input_string.split()
    new = ''
    for i in range(-1,-(len(words))-1,-1):
        new = new + words[i] + " "
    new = new.strip()
    return new

# Example usage:
user_input = input("Enter any string:")
result = reverse_words(user_input)
print(result)