# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JttHq2PyT9G8yq5Bbhsd3_zndaSr3osP
"""

import pandas as pd
import numpy as np


df = pd.DataFrame(np.random.randint(low=0,high=101,size=(20,2)))
print(f"Scores lying below 100% of scores in physics and chemistry is {df.quantile(1)[0]} and {df.quantile(1)[1]} respectively ")
print(f"Scores lying below 95% of scores in physics and chemistry is  {df.quantile(.95)[0]} and {df.quantile(.95)[1]} respectively ")
print(f"Scores lying below 50% of scores in physics and chemistry is  {df.quantile(.5)[0]} and {df.quantile(.5)[1]} respectively ")