# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

def new_string(s):
    if(len(s)%4!=0):
        return s
    x = ''
    for i in range(len(s)-1,-1,-1):
        x = x + s[i]
    return x

s1 = input("Enter string:")
result = new_string(s1)
print(result)