# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

n = int(input("Enter the value of n:"))
print("Enter the values for list:")
c = 0
sum = 0
list1 = []

while(c!=n):
    x = int(input())
    list1.append(x)
    c = c + 1

element = int(input("Enter the element to be found:"))
c = 0
for i in range(0,n,1):
    if(list1[i] == element):
        c = c + 1
    else:
        continue

if(c>0):
    print("Element is the list")
else:
    print("Element is not in the list")