# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Mu7mK4-bQJwqTMNuis9LcLBIfMc1qfi
"""

# To display all numbers that are not divisible by 7 and 11
for i in range(1,101):
    if(i%7==0 and i%11==0):
        continue
    else:
        print(i)

