# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Mu7mK4-bQJwqTMNuis9LcLBIfMc1qfi
"""

for i in range(5):
    print("")
    if(i<=2):
        for k in range(i+1):
            print("*",end=" ")
    else:
        for k in range(i%2+1):
            print("*",end=" ")

