# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZQamPoJ7CjFYrumHYNvOyl4hCQ-RM-_A
"""

import numpy as np

temperatures = [25.5, 26.0, 24.5, 23.0, 22.5, 27.0, 26.5, 25.0, 23.5, 24.0]
num_t = np.array(temperatures)
print(num_t)

