# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

list_alphabet = ['A','B','C','D','E','F','G','H','I','J']

# First Operation
print(list_alphabet[0:3])
# Second Operation
print(list_alphabet[4:7])
#Third Operation
print(list_alphabet[6:])