# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

tuple_marks = ((45,67,89),(23,56,89),(56,87,86),(76,56,35),(35,56,76))

# To display marks of fourth student
print(tuple_marks[3])
# To display marks obtained by second student in first subject
print(tuple_marks[1][0])
# Total Marks obtained by each student and avrage of each student
list1 = []
sum = 0
for i in range(len(tuple_marks)):
    sum = 0
    for j in tuple_marks[i]:
        sum = sum + j
    list1.append(sum/5)
    print(f"Student{i+1} gets total of {sum} marks and a avaerage of {sum/5}")
# Average of average
sum1 = 0
for i in list1:
    sum1 = sum1 + i
print(f"The avarage marks obtained by all student is {sum1/5}")

# Maximum and minimum marks for each student
for i in range(len(tuple_marks)):
    max = tuple_marks[i][0]
    min = tuple_marks[i][0]
    for j in tuple_marks[i]:
        if(j>max ):
            max = j
        if(j<min):
            min = j
    print(f"Student{i+1} gets maximum marks of {max} and minimum marks of {min}")