# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

s = "hello world"
list1 = s.split()
new = ""
for i in list1:
    new = new + i.capitalize() + " "
print(new.strip())