# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JttHq2PyT9G8yq5Bbhsd3_zndaSr3osP
"""

import pandas as pd

df = pd.DataFrame({
    "User_ID": [1001,1001,1001,1001,1002,1003,1004,1004,1004,1004,1005,1005,1005,1005,1005],
    "Product_ID": ["P1","P2","P3","P4","P2","P3","P1","P2","P3","P4","P1","P2","P3","P4","P5"],
    "Purchase": [100,200,300,500,200,400,200,300,400,500,100,200,300,400,500]
})

df2 = pd.DataFrame(df.groupby("User_ID").agg({"Purchase": ['mean']}))

def match(x):
    for i in df2.index:
        if i == x:
            return df2.loc[i, ('Purchase', 'mean')]

df['User_Mean'] = df['User_ID'].apply(match)

print(df)