# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1roF59jyJ80Gy5dh1yKNt9hnp6Hl6Mc6z
"""

# To calculate simple interest

p = float(input("Enter the principal amount:"))
r = float(input("Enter the rate(in percent):"))
t = int(input("Enter the time period:"))
si = p*r*t/100
print("Simple interest is %.2f"%(si))

# To calculate compound interest

p = float(input("Enter the principal amount:"))
r = float(input("Enter the rate(in percent):"))
t = int(input("Enter the time period:"))

ci = (p*((1+r/100)**(t)))-p
print("Compound interest is %.2f"%(ci))