# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Mu7mK4-bQJwqTMNuis9LcLBIfMc1qfi
"""

fn = input("Enter firstname:")
ln = input("Enter lastname:")
print(f"Hello {fn} {ln}")
print("Welcome to Python!")