# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Mu7mK4-bQJwqTMNuis9LcLBIfMc1qfi
"""

num1 = int(input("Enter the value of num1:"))
num2 = int(input("Enter the value of num2:"))
if(num1>num2):
    print("num1 is greater than num2")
    print(f"num1/num2 = {num1/num2}")
    print(f"Quotient is {(num1//num2)}")
    print(f"Remiander is {num1%num2}")
else:
    print("num1 is greater than num2")
    print(f"num1/num2 = {num2 / num1}")
    print(f"Quotient is {(num2 // num1)}")
    print(f"Remiander is {num2 % num1}")