# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

n = int(input("Enter the value of n:"))
print("Enter the values for list:")
list1 = []
for i in range(n):
    x = int(input())
    list1.append(x)
max = list1[len(list1)//2]
for i in range(len(list1)//2,len(list1)):
    if(list1[i]>max):
        max = list1[i]

print(f"Maximum value from second half of list is {max}")