# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

import random

list1 = []
for i in range(10):
    list1.append((random.randint(1,100),random.randint(1,100)))

tuple1 = tuple(list1)
print(tuple1)

c = 0
for i in range(len(tuple1)):
    if(tuple1[i][0]%2 !=0 and tuple1[i][1]%2 != 0):
     c = c + 1

print(f"tuple1 has {c} number of pairs having both values odd")