# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Mu7mK4-bQJwqTMNuis9LcLBIfMc1qfi
"""

# Program to calculate Momentum
mass = float(input("Enter the mass of object(in kilograms):"))
velocity = float(input("Enter the velocity of object(in meters per second):"))
momentum = mass*((velocity)**2)
print("Momentum is %.2f"%(momentum))