# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1roF59jyJ80Gy5dh1yKNt9hnp6Hl6Mc6z
"""

# Use of single quotes
print('This string contains single quotes')
# Use of double quotes
print("This string contains double quotes")
# Use of triple quotes
print('''This string contains triple quotes and
it is a multiline string''')