# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

def string_startswith(s1,s2):
    if(s1.startswith(s2)):
        print(f"{s1} starts with {s2}")
    else:
        print(f"{s1} does not starts with {s2}")

s1 = input("Enter string:")
s2 = input("Enter string that our stirng to start with:")
string_startswith(s1,s2)