# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZQamPoJ7CjFYrumHYNvOyl4hCQ-RM-_A
"""

import numpy as np

np_arr  = np.array([[99,45,67,34,53],[45,43,56,54,89],[96,74,55,63,32],[89,74,87,32,98],[32,76,89,97,87]])
arr_dim = np_arr.shape
list1 = ["Maths","Physics","Chemistry","English","Computer Science"]
# Max value in each subject
max = np_arr.max(axis = 0)
# Min value in each subject
min = np_arr.min(axis=0)
for i in range(0,len(list1)):
    print(f"Highest marks in {list1[i]} subject is {max[i]}")
    print(f"Highest marks in {list1[i]} subject is {min[i]}")
# Adding marks of two more students in our array
np_arr = np.vstack([np_arr,[[67,35,89,76,54],[45,34,58,79,87]]])
print(np_arr)

