# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

def strip_characters(s,c):
    new = ""
    list1 = []
    for i in c:
        list1.append(i)
    for i in range(len(s)):
        c = 0
        for j in range(len(list1)):
            if(s[i] == list1[j]):
                c = c+1
                break
        if(c<1):
            new = new + s[i]
    return new

user_input = input("Enter string:")
characters_to_remove = input("Enter characters to remove:")
result = strip_characters(user_input,characters_to_remove)
print(result)