# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

def filter_words_starting_with(alphabet, word_list):
    filtered_words = [word for word in word_list if word.startswith(alphabet)]
    return filtered_words

# Example usage:
word_list = ["apple", "banana", "orange", "grape", "avocado", "pear"]

user_alphabet = input("Enter an alphabet: ").lower()  # Convert input to lowercase for case-insensitivity
filtered_words = filter_words_starting_with(user_alphabet, word_list)

if filtered_words:
    print(f"Words starting with '{user_alphabet}': {filtered_words}")
else:
    print(f"No words found starting with '{user_alphabet}'.")