# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Mu7mK4-bQJwqTMNuis9LcLBIfMc1qfi
"""

# To display student details
name = input("Enter student name: ")
age = int(input("Enter student age: "))
grade = input("Enter student grade: ")

print(f"Student Details: {name} - {age} - {grade}")