# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

user_input = input("Enter any string:")
n = int(input("Enter the value of n:"))

new = ""
for i in range(0,n):
    new = new + user_input[i]

print(new)