# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JttHq2PyT9G8yq5Bbhsd3_zndaSr3osP
"""

import pandas as pd
import numpy as np


df = pd.DataFrame({"A":[1.0,4.0,7.0,np.nan],
                   "B": [2,5,8,np.nan],
                   "C":[3.0,6.0,9.0,np.nan]
                   })

print(df.agg(['mean', 'median', 'min', 'max', 'std']))