# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

user_input = input("Enter any string:")
list1 = []
for i in user_input:
    list1.append(i.lower())
list2 = list1
list2 = sorted(list2)
new  = ''
for i in list2:
    new  = new + i
print(new)
dict1 = {}
for i in range(0,len(list1)):
    x = list1[i]
    if(x == "$"):
        continue
    c = 1
    for j in range(i+1,len(list1)):
        if(x == list1[j]):
            c = c + 1
            list1[j] = "$"
        else:
            continue
    dict1[x] = c
print(dict1)