# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

user_input = int(input("Enter an integer:"))
new = str(user_input)

if(len(new)%3==0):
    r = len(new)//3 - 1
else:
    r = len(new)//3

c = -1
result = ""
for i in range(-1,-(len(new) + r+ 1),-1):
    if(i%4==0):
        result = result + ","
    else:
        result = result + new[c]
        c = c - 1

print(result[::-1])