# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZQamPoJ7CjFYrumHYNvOyl4hCQ-RM-_A
"""

import numpy as np

np_arr = np.random.random((5,5,5))
arr_shape = np_arr.shape
for i in range(arr_shape[0]):
    for j in range(arr_shape[1]):
        for k in range(arr_shape[2]):
            if(i%2!=0 and j%2==0):
                print(np_arr[i][j][k])

