# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Mu7mK4-bQJwqTMNuis9LcLBIfMc1qfi
"""

# To calculate total salary
salary = float(input("Enter your basic pay:"))
hra = .1*salary
ta = .05*salary
total = hra + ta + salary
print("Your total salary is %.2f"%(total))