# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZQamPoJ7CjFYrumHYNvOyl4hCQ-RM-_A
"""

import numpy as np
tuple1 = ((2,3,1),(4,6,8))
np_arr = np.array(tuple1)
print(np_arr)
print(tuple(np_arr))

