# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

def delete_substring(main_string, substring):
    result = main_string.replace(substring, '')
    return result

# Example usage:
main_str = input("Enter the main string: ")
substring_to_delete = input("Enter the substring to delete: ")

result = delete_substring(main_str, substring_to_delete)
print(result)