# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Mu7mK4-bQJwqTMNuis9LcLBIfMc1qfi
"""

user_input = float(input("Enter the amount to be paid:"))

if(user_input>=30000):
    discount = 30
elif(user_input>=20000):
    discount = 20
elif(user_input>=10000):
    discount = 10
else:
    discount = 5

amount = user_input - (discount/100)*user_input
print("Amount to be paid by custmer is %.2f"%amount)