# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

def palindroe(input_string):
    c = 0
    l = len(input_string)
    for i in range(l//2):
        if(input_string[i] == input_string[l-i-1]):
            c = c + 1
    if(c==l//2):
        print("It is a palindrome")
    else:
        print("It is not a palindrome")
# Example usage:
user_input = input("Enter a string: ")
palindroe(user_input)