# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

n = int(input("Enter the value of n:"))
print("Enter the values for list:")
list1 = []
c = 0
while(c!=n):
    x = int(input())
    list1.append(x)
    c = c + 1

dict1 = {}
for i in range(0,n):
    if (list1[i] == '$'):
        continue
    l = 1
    x = list1[i]
    for j in range(i+1,n):
        if(x == list1[j]):
            l = l + 1
            list1[j] = '$'
    dict1[x] = l

for i,j in dict1.items():
    print(f"Number {i} comes {j} times")