# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LyqacOArbQ9XwM6gA4FVz9CR047eOna-
"""

# String Concatenation

# To peform String Concatenation by using + operator
str1 = "Hello"
str2 = " World"
result = str1+str2
print(result)
# To peform String Concatenation by using += operator
result = "Hello"
result += " World"
print(result)
# To perform String concatenation by using join method
strings = ["Hello"," World"]
result.join(strings)
print(result)
# To peform String concatenation by placing strings side by side
str1 = "Hello"
str2 = " World"
result = f"{str1}{str2}"
print(result)