# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

user_input = float(input("Enter a floating point number:"))
if(user_input>0):
    print("+%.2f"%(user_input))
else:
    print("%.2f" % (user_input))