# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

def custom_replace(main_string, old_substring, new_substring):
    result = ""
    i = 0
    while i < len(main_string):
        if main_string[i:i+len(old_substring)] == old_substring:
            result += new_substring
            i += len(old_substring)
        else:
            result += main_string[i]
            i += 1
    return result

# Example usage:
main_str = input("Enter the main string: ")
old_sub = input("Enter the substring to replace: ")
new_sub = input("Enter the replacement string: ")

result = custom_replace(main_str, old_sub, new_sub)
print(result)