# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

s = "hElLo WoRlD"

new = ""
for i in s:
    if(i.isupper()):
        new = new + i.lower()
    elif(i.islower()):
        new = new + i.upper()
    else:
        new = new + i
print(new)