# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_Mu7mK4-bQJwqTMNuis9LcLBIfMc1qfi
"""

user_hourly_wage = int(input("Enter hourly wage:"))
user_regular_hour = float(input("Enter regualar hours you worked:"))
user_overtime_hour = float(input("Enter overtime hours you worked:"))

print(f"Your total weekly pay is {user_overtime_hour*user_hourly_wage+user_regular_hour*user_hourly_wage}")