# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

def add_prefix_to_lines(text, prefix):
    lines = text.splitlines()
    list1 = []
    for line in lines:
        new = prefix + "" + line
        list1.append(new)
    for i in list1:
        print(i)

# Example usage:
original_text = "Line 1\nLine 2\nLine 3"
prefix_text = "Prefix: "
add_prefix_to_lines(original_text, prefix_text)