# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

str1 = input("Enter the string:")
str2 = input("Enter string to be appended:")

str3 = "".join([str1,str2])
print(str3)