# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RrTyusaElUsDEFrCSyJ9PaWz3Vpx1s04
"""

def new_string(s):
    if(len(s)<2):
        return s
    new = s[len(s)-1] + s[1:-1] + s[0]
    return new

user_input = input("Enter any string:")
result = new_string(user_input)
print(f"{result}")