# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQHoX16w_jmxRRFfL1rpzUHomhb_SPK1
"""

name = input("Enter your name:")
list_name = name.split()
new = ""
for i in list_name:
    new = new + i[0]
new = ".".join(new)
print(new.upper())