# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K8BztIo6umoUVJKZ8xH1u2PSvbkL_KMK
"""

def new_String(String):
    if(len(user_input)<2):
        return ""
    else:
        print(f"New String is {String[:2]+String[-2:]}")

user_input = input("Enter any string:")
new_String(user_input)