# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1apvBYBoFA1BIel77UBxoAptEiJjF17cT
"""

list1 = []
j = 97
for i in range(26):
    list1.append((i+1)*chr(j))
    j = j + 1
print(list1)